builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/sul/main.go
    binary: sul
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
